dist: xenial   # required for Python >= 3.7
language: python # => 1

python: # => 2
  - "3.7"

services: # => 3
  - mysql

env: # => 4
  -DJANGO=2.2 DB=mysql

install: # => 5
  - pip install -r RaceOrganizerServer/requirements.txt

before_script: # => 6
  - mysql -u root -e "CREATE DATABASE raceorganizer CHARACTER SET UTF8;"
  - mysql -u root -e "CREATE USER 'test'@'%' IDENTIFIED BY 'test';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON raceorganizer.* to 'test'@'%';"
  - mysql -u root -e "ALTER USER test CREATEDB;"
  - mysql -u root -e "FLUSH PRIVILEGES"

script: # => 7
  - cd RaceOrganizerServer
  - python manage.py test
