# Generated by Django 2.1.7 on 2019-03-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('personal_id', models.CharField(max_length=32, unique=True)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('isOrganizer', models.BooleanField(default=False)),
            ],
        ),
    ]
