# Generated by Django 2.2 on 2019-04-07 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('personal_id', models.CharField(max_length=32, unique=True)),
                ('birth_date', models.DateField()),
                ('email', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('race_id', models.AutoField(primary_key=True, serialize=False)),
                ('edition', models.CharField(max_length=32, unique=True)),
                ('sponsor', models.CharField(max_length=32)),
                ('place', models.CharField(max_length=32)),
                ('time', models.DateTimeField()),
                ('prize', models.IntegerField()),
                ('price', models.IntegerField()),
                ('helpers', models.ManyToManyField(related_name='helper', to='api.Person')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer',
                                                to='api.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Person')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Race')),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='runners',
            field=models.ManyToManyField(through='api.Runner', to='api.Person'),
        ),
    ]
