# Generated by Django 2.2 on 2019-04-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.CharField(max_length=32, unique=True)),
                ('sponsor', models.CharField(max_length=32)),
                ('place', models.CharField(max_length=32)),
                ('time', models.CharField(max_length=32)),
                ('prize', models.CharField(max_length=32)),
                ('price', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='isRunner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='isVolunteer',
            field=models.BooleanField(default=False),
        ),
    ]
