# Generated by Django 2.2 on 2019-04-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='helpers',
            field=models.ManyToManyField(blank=True, related_name='helper', to='api.Person'),
        ),
        migrations.AlterField(
            model_name='race',
            name='runners',
            field=models.ManyToManyField(blank=True, through='api.Runner', to='api.Person'),
        ),
        migrations.AlterField(
            model_name='race',
            name='sponsor',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
